version: '3.8'
services:
  gateway:
    image: 01-work-gateway:latest
    container_name: gateway
    ports:
      - "3000:3000"
  atlantiplex:
    image: 01-work-atlantiplex:latest
    container_name: atlantiplex
    ports:
      - "3001:3001"
  nginx:
    image: nginx:latest
    container_name: nginx_reverse
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - gateway
      - atlantiplex
